name: openachp
channels:
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - matplotlib
  - jupyter
  - git
  - ipywidgets
  - pandas
  - xarray
  - pip:
    - tabulate
    - CoolProp
    - pyvtk

